// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQi03IOnrFrrq4Oog028RG1_ak5uQr6hA',
    appId: '1:547015125596:web:e31e27e4ea396544ec9499',
    messagingSenderId: '547015125596',
    projectId: 'prev-out-5e51a',
    authDomain: 'prev-out-5e51a.firebaseapp.com',
    storageBucket: 'prev-out-5e51a.appspot.com',
    measurementId: 'G-94E33F18YN',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRPTNZHEbP2Kv5a2MLh1o0jjq-NDv656s',
    appId: '1:547015125596:ios:98b3c8b65e84ac45ec9499',
    messagingSenderId: '547015125596',
    projectId: 'prev-out-5e51a',
    storageBucket: 'prev-out-5e51a.appspot.com',
    iosBundleId: 'com.example.prevOut',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQi03IOnrFrrq4Oog028RG1_ak5uQr6hA',
    appId: '1:547015125596:web:4d647300b1cdb021ec9499',
    messagingSenderId: '547015125596',
    projectId: 'prev-out-5e51a',
    authDomain: 'prev-out-5e51a.firebaseapp.com',
    storageBucket: 'prev-out-5e51a.appspot.com',
    measurementId: 'G-RKBJ4ZCW6B',
  );
}
